### PR TITLE
Update export.py with LogsChart chart type

### PR DESCRIPTION
**Pull request by joem-splunk**
Added LogsChart with the tf_type of signalfx_log_view to allow this export script too handle new Logs Chart.

### CODE REVIEW

**Comment by joem-splunk** [comment]
I have read the Code of Conduct and I hereby accept the Terms

**Comment by joem-splunk** [comment]
`I have read the Code of Conduct and I hereby accept the Terms`

**Comment by greatestusername-splunk** [comment]
Currently the CLA workflow appears to be broken. Trying to dig up what our path forward is.

What was your previous account name? @jadbSFx  right?

**Comment by joem-splunk** [comment]
@greatestusername-splunk nope! Always been joem-splunk. That's another Joe :)

**Comment by joem-splunk** [comment]
All good! Thanks for the assistance! @greatestusername-splunk

**Comment by greatestusername-splunk** [comment]
recheck

**Review by greatestusername-splunk — APPROVED** [review]

**Review by greatestusername-splunk — APPROVED** [review]

**Comment by greatestusername-splunk** [comment]
recheck

**Comment by greatestusername-splunk** [comment]
I have read the Code of Conduct and I hereby accept the Terms

**Comment by greatestusername-splunk** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by greatestusername-splunk** [comment]
I have read the Code of Conduct and I hereby accept the Terms

I have read the CLA Document and I hereby sign the CLA

**Comment by greatestusername-splunk** [comment]
@joem-splunk mind messaging jeremyh on slack?

**Comment by joem-splunk** [comment]
I have read the Code of Conduct and I hereby accept the Terms

I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
