### PR TITLE
Add SNMP dashboard

### PR DESCRIPTION
**Pull request by smathur-splunk**

### CODE REVIEW

**Comment by smathur-splunk** [comment]
I have read the CLA and I hereby accept the Terms

**Comment by smathur-splunk** [comment]
recheck

**Comment by smathur-splunk** [comment]
I have read the Code of Conduct and I hereby accept the Terms

**Comment by smathur-splunk** [comment]
recheck

**Review by jadbSFx — APPROVED** [review]
Imported and validated with SC4SNMP data

**Pull request merged**
