### PR TITLE
Main

### PR DESCRIPTION
**Pull request by aschalock-splunk**
I have read the CLA Document and I hereby sign the CLA
I have read the Code of Conduct and I hereby accept the Terms

Initial Commit: New Folder in the integration-examples titled: observability-microservices-demo. This folder contains a readme.md file. 

The readme.md contains an OpenTelemetry Quick Start is a guide to how to quickly get started evaluating the features of Splunk Observability Cloud. This exercise is using the Splunk branch of the [Online Boutique microservices demo application](https://github.com/signalfx/microservices-demo-rum "microservices-demo-rum github repository") instrumented with Application Peformance Monitoring and Real User Monitoring. The [Splunk OpenTelemetry Collector for Kubernetes](https://github.com/signalfx/splunk-otel-collector-chart "Splunk OpenTelemetry Collector for Kubernetes Repository") is also installed along side the microservices demo relaying signals to Splunk Observability Cloud as well as providing Infrastructure Metrics.

### CODE REVIEW

**Comment by aschalock-splunk** [comment]
This is ready for review please reach out prior to merging if you have any questions or suggestions.

**Comment by aschalock-splunk** [comment]
I have read the Code of Conduct and I hereby accept the Terms

**Comment by greatestusername-splunk** [comment]
recheck

**Review by greatestusername-splunk — APPROVED** [review]
Ran through these instructions.
Looks good to me!
Happy to have more integration examples and this one lights up all of Splunk Observability.

**Comment by aschalock-splunk** [comment]
Thank you for reviewing!

**Pull request merged**
