### PR TITLE
bblinderman - 01/17/24

### PR DESCRIPTION
**Pull request by bblinder**
Cleaning up the export script, making it more readable and optimizing it a bit more for simplicity.

### CODE REVIEW

**Review by greatestusername-splunk — APPROVED** [review]
Thanks for contributing! This all looks fine to me.

I'm requesting @rcastley review this also as he uses the Terraform Jumpstart quite a bit and has the most context.

**Comment by greatestusername-splunk** [comment]
Also @bblinder please respond with comments for CLA and COC checks
```
I have read the CLA Document and I hereby sign the CLA
```

```
I have read the Code of Conduct and I hereby accept the Terms
```

**Review by rcastley — APPROVED** [review]

**Comment by bblinder** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by bblinder** [comment]
I have read the Code of Conduct and I hereby accept the Terms

**Comment by greatestusername-splunk** [comment]
recheck

**Comment by bblinder-splunk** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by bblinder-splunk** [comment]
I have read the Code of Conduct and I hereby accept the Terms

**Pull request merged**
