### PR TITLE
Update exec dashboards (and exec dashboards in jumpstart)

### PR DESCRIPTION
**Pull request by greatestusername**
- Remove "Billing" verbiage and replace with "License"
- Remove old LO notice
- Add one Synthetics datapoints chart to Usage Overview
- Remove High Resolution IMM chart from Usage Overview as requested

### CODE REVIEW

**Comment by greatestusername** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by greatestusername** [comment]
I have read the Code of Conduct and I hereby accept the Terms

**Comment by greatestusername-splunk** [comment]
CLA and COC has been signed previously by user
https://github.com/splunk/cla-agreement/blob/main/signatures/version1/cla.json#L932-L938

**Review by gregleffler — APPROVED** [review]
The marketing person in me enjoys this messaging update and it looks good to me.

**Review by greatestusername-splunk — APPROVED** [review]
All looks good to me and tests fine from TF

**Pull request merged**
