### PR TITLE
Apple M1 Driver for Docker and Minikube

### PR DESCRIPTION
**Pull request by aschalock-splunk**
Updating the readme to include start-up instructions for Apple M1, docker and minikube.

### CODE REVIEW

**Comment by aschalock-splunk** [comment]
And now with a more agrees! 
I have read the CLA Document and I hereby sign the CLA
I have read the Code of Conduct and I hereby accept the Terms

**Review by aschalock-splunk — COMMENTED** [review]
I have read the CLA Document and I hereby sign the CLA
I have read the Code of Conduct and I hereby accept the Terms

**Comment by aschalock-splunk** [comment]
recheck

**Review by aschalock-splunk — COMMENTED** [review]
I have read the CLA Document and I hereby sign the CLA

**Comment by aschalock-splunk** [comment]
I have read the Code of Conduct and I hereby accept the Terms

**Comment by aschalock-splunk** [comment]
recheck

**Review by aschalock-splunk — COMMENTED** [review]
I have read the Code of Conduct and I hereby accept the Terms

**Review by aschalock-splunk — COMMENTED** [review]
I have read the CLA Document and I hereby sign the CLA

**Comment by aschalock-splunk** [comment]
I have read the CLA and I hereby accept the Terms

**Comment by aschalock-splunk** [comment]
I have read the Code of Conduct and I hereby accept the Terms

**Comment by aschalock-splunk** [comment]
recheck

**Review by jadbSFx — APPROVED** [review]
LGTM

**Pull request merged**
