### PR TITLE
Oracle cloud content

### PR DESCRIPTION
**Pull request by jadbSFx**
Two dashboars illustrating Oracle Cloud integration.

### CODE REVIEW

**Comment by greatestusername-splunk** [comment]
@jadbSFx Is this finished / ready for review? Let me know and I'll be happy to take a swing through!

**Comment by jadbSFx** [comment]
Yes, ready for review. Thanks!

**Comment by greatestusername-splunk** [comment]
This is great! Thank you for making and adding it!

At some future point would it be worth the effort of moving / copying over https://github.com/splunk/oracle-cloud-examples-splunk-observability to this contrib repo in the integrations folder?

Let me know and I'll see about adding it to the backlog.

**Review by greatestusername-splunk — APPROVED** [review]
Thanks for contributing this!

**Comment by jadbSFx** [comment]
FYI, while the content here is done, the connectors to OCI are only available internally:
https://github.com/splunk/oracle-cloud-examples-splunk-observability/tree/master/samples/oci-monitoring-metrics-to-splunk-observability-python
https://github.com/splunk/oracle-cloud-examples-splunk-observability/tree/master/samples/oci-logs-splunk-hec

My intent is to get these contributed upstream to Oracle's repository, but that is pending approval of contribution to open source. For now putting the content out here would at least help internal users.

**Pull request merged**
