### PR TITLE
OpenTelemetry Receiver to Splunk Observability dashboard generator (Terraform configs)

### PR DESCRIPTION
**Pull request by greatestusername**
Python script for taking the metrics named in any given OpenTelemetry Receiver's `metadata.yaml` and create a dashboard for Splunk Observability with those metrics as a Terraform config. Saves time for users who need/want to use a contrib receiver but don't want to hunt down all the possible metrics and add them to a dashboard.

- Included a folder of generated dashboards as well (`observability-tf-configs`)
- `otel-receiver-yaml` directory contains current yaml files for receivers. Can also be pulled down by script.

**NOTE:** These dashboards are GENERATED and are NOT a replacement for Out Of The Box dashboard/content in Splunk Observability. This is also noted in the README.md.

### CODE REVIEW

**Comment by greatestusername-splunk** [comment]
recheck

**Comment by greatestusername** [comment]
recheck

**Comment by greatestusername** [comment]
## Generate dashboard for a single receiver
Install the requirements and run `otel-dashboard-o11y.py` with the `--file_path` option pointing the `metadata.yaml` file for the receiver you'd like to generate from. 

Note: The Terraform configuration will print to STDOUT which can be piped to a `.tf` file. 
```
pip3 install -r requirements.txt
python3 otel-dashboard-o11y.py --file_path ./metadata.yaml
```

## Generate dashboards for many receivers
If the `--file_path` argument is not used the script will look in the local directory [`./otel-receiver-yaml/`](./otel-receiver-yaml/) for available receiver `metadata.yaml` files with metrics sections. Generated Terraform configurations will be placed in the local directory [`./observability-tf-configs`](./observability-tf-configs/).

`pull-otel-yaml.py` can be used to pull down all [receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver) configs with a `metrics` section and place them in the `./otel-receiver-yaml` directory. To avoid api rate limiting during this process a Github PAT token can be provided with the environment variable `$GITHUB_PAT_TOKEN`.
```
pip3 install -r requirements.txt
python3 pull-otel-yaml.py                          
Metadata.yaml with 'metrics' section extracted from activedirectorydsreceiver
Metadata.yaml with 'metrics' section extracted from aerospikereceiver
...
```

**Review by billg-splunk — APPROVED** [review]
LGTM

**Pull request merged**
